AC_DEFUN([EVENTD_I18N], [
AC_REQUIRE([IT_PROG_INTLTOOL])dnl
EVENTD_EVENT_RULE="`echo "${INTLTOOL_DESKTOP_RULE}" | sed -e s:%.desktop:%.event:g`"
AC_SUBST([EVENTD_EVENT_RULE])
AM_SUBST_NOTMAKE([EVENTD_EVENT_RULE])
])
